### ISSUE TITLE
[Feature] - Accept external routing based on [id] 

### ISSUE THREAD

**Issue by RobJJ** [parvathykrishnank/Climate-Change-Screening-RTD#1]
Add the ability for an external application to reroute a user to a specific threshold in the RTD based on the [id] slugged passed in payload

Please add a simple doc on how to route to this page

**Comment by parvathykrishnank** [comment]
A route for viewing individual records in the Risk Threshold Database has been added. This route includes two views:
- A view when the record is found.
- A view when the record is not found.

Each record, identifiable by the ID field in the database, can be viewed with the following route: https://gpbprtd.eu.pythonanywhere.com/record/<RECORD_ID>. If the record is found, the following view is returned.

<img width="1792" alt="image" src="https://github.com/parvathykrishnank/Climate-Change-Screening-RTD/assets/42402451/8a405f70-61f7-411b-83d6-30ad19755322">

If the ID is not found in the database, an alert is shown as follows -
<img width="1792" alt="image" src="https://github.com/parvathykrishnank/Climate-Change-Screening-RTD/assets/42402451/90669c4c-dad0-4ec1-b2ae-c59e9b5178ab">
